apiVersion: v1
kind: Service
metadata:
  name: gitops-devops-pipeline
  labels:
    app: gitops-devops-pipeline
spec:
  selector:
    app: gitops-devops-pipeline
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
