name: CI - Build & Publish + Update GitOps

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-push-and-update-gitops:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/gitops-devops-pipeline-app
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg APP_COMMIT=${{ github.sha }} \
            -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/gitops-devops-pipeline-gitops
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: gitops

      - name: Update image tag in GitOps manifests
        run: |
          set -e
          FILE="gitops/apps/myapp/kustomization.yaml"
          if [ ! -f "$FILE" ]; then
            echo "File not found: $FILE"
            exit 1
          fi

          # Update the image tag (kustomize images block)
          sed -i "s|newTag: .*|newTag: ${IMAGE_TAG}|g" "$FILE"

          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add apps/myapp/kustomization.yaml
          git commit -m "chore(gitops): deploy myapp image ${IMAGE_TAG}" || echo "No changes to commit"
          git push
